title: Iowa Civic Action Toolkit
description: An open-source template for replicable citizen advocacy, macro-sociology analytics, and public interest pitches.
theme: jekyll-theme-cayman

# Social Media Previews (Read automatically by jekyll-seo-tag plugin)
image: /assets/thumbnail.jpg

# Active compilation plugins
plugins:
  - jekyll-seo-tag