title: Iowa Civic Action Toolkit
description: An open-source template for replicable citizen advocacy, macro-sociology analytics, and public interest pitches.
theme: jekyll-theme-cayman

# GitHub Pages Routing
url: "https://mmonfils.github.io"
baseurl: "/civic-action-toolkit"

# Social Preview & Interface Assets
og_image: "https://mmonfils.github.io/civic-action-toolkit/assets/thumbnail.jpg"
favicon: "https://mmonfils.github.io/civic-action-toolkit/assets/favicon.png"